Factory.define :article do |article|
  article.category_id '1'
  article.param 'MyString'
  article.title 'MyString'
  article.sub_title 'MyString'
  article.short_content 'MyText'
  article.content 'MyText'
  article.show_time '2009-07-18 23:15:30'
  article.source 'MyString'
  article.source_link 'MyString'
  article.author_id '1'
  article.state_id '1'
  article.sticky_level '1'
  article.comments_count '1'
end
